name: Build
on:
  workflow_call:
    inputs:
      rust:
        required: true
        type: string
      target:
        required: true
        type: string

env:
  RUSTFLAGS: '--deny warnings'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ inputs.rust }}
          targets: ${{ inputs.target }}

      - name: Checkout CI scripts
        if: ${{ ! contains(inputs.target, 'x86_64') }}
        uses: actions/checkout@v4
        with:
          repository: 'eldruin/rust-driver-ci-scripts'
          ref: 'master'
          path: 'ci'

      - run: ./ci/patch-no-std.sh
        if: ${{ ! contains(inputs.target, 'x86_64') }}

      - run: cargo build --target=${{ inputs.target }}
